### ISSUE TITLE
Missing Type: AttendeePicker

### ISSUE THREAD

**Issue by laultman** [microsoftgraph/msgraph-sample-uwp#60] opened 2023-11-17 09:25 UTC
**Where did you get the code?**
Downloaded and followed instructions.

**Describe the bug**
Type AttendeePicker is not found.

**To Reproduce**
Follow the instructions for the tutorial.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Dependency versions**
 - Authentication library (MSAL, etc.) version:
 - Graph library (Graph SDK, REST library, etc.) version:  

**Additional context**

**Comment by jasonjoh** [comment] 2023-11-17 14:52
Possibly a duplicate of #40. Can you try **Clean Solution** and then **Rebuild Solution**?

**Comment by laultman** [comment] 2023-11-17 19:23
That worked. But found other issues as well #61

**Closed** 2023-11-17 19:35 UTC
Labels: needs attention :wave:
